spring.application.name=sai
    # ===============================
    # DATABASE CONFIG
    # ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

    # ===============================
    # JPA / HIBERNATE
    # ===============================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

jwt.secret=mysupersecurejwtsecretkeyforhs256algorithm123456
jwt.expiration=86400000

file.upload-dir=uploads/


    # ===============================
    # OPENAI CONFIG (SPRING AI)
    # ===============================
   # spring.ai.openai.chat.options.model=gpt-4.1-mini

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=tinyllama