
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

file.upload-dir=uploads/
cloud.name=CLOUD_NAME
cloud.apikey=CLOUD_APIKEY
cloud.secret=CLOUD_SECRET
spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB